security:
    encoders:
        App\Entity\UserClient:
            algorithm: bcrypt
            cost: 12
        App\Entity\User: plaintext
    providers:
        form_database:
            entity:
                class: App\Entity\UserClient
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path: /logout
                target: /

            form_login:
                login_path: security_login_client
                check_path: security_login_client

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/account, roles: ROLE_CLIENT }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
